<?php

namespace App\Http\Controllers;

use App\Ai\Agents\BlogPostGenerator;
use App\Http\Requests\GeneratePostRequest;
use Laravel\Ai\Responses\StreamableAgentResponse;

class GenerateController extends Controller
{
    /**
     * Stream a blog post generated by the AI agent as Server-Sent Events.
     */
    public function stream(GeneratePostRequest $request): StreamableAgentResponse
    {
        $agent = new BlogPostGenerator(
            topic: $request->input('topic'),
            title: $request->input('title'),
            tone: $request->input('tone'),
            keywords: $request->input('keywords'),
            length: $request->input('length'),
        );

        return $agent
            ->stream($agent->userPrompt(), timeout: 120)
            ->usingVercelDataProtocol();
    }
}
